# Generated by Django 4.1.7 on 2023-04-11 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('color', models.CharField(max_length=100)),
                ('detail1', models.CharField(max_length=80)),
                ('detail2', models.CharField(max_length=80)),
                ('detail3', models.CharField(max_length=80)),
                ('detail4', models.CharField(max_length=80)),
                ('detail5', models.CharField(max_length=80)),
                ('detail6', models.CharField(max_length=80)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.brand')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.productcategory')),
            ],
        ),
    ]
