# Generated by Django 4.1.7 on 2023-04-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_productimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
