# Generated by Django 4.1.7 on 2023-04-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0004_delete_productimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('color', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.brand')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.productcategory')),
            ],
        ),
    ]
