# Generated by Django 4.1.7 on 2023-04-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0006_remove_productimages_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('detail1', models.CharField(max_length=50)),
                ('detail2', models.CharField(max_length=50)),
                ('detail3', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.brand')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.productcategory')),
            ],
        ),
    ]
